### ISSUE TITLE
New validator

### ISSUE THREAD

**Issue by Tachyonica** [eth2353/eth2.tax#11]
Hi. I inducted new validators and now your awesome tool is hanging - any way to fix? Thanks very much!

**Comment by eth2353** [comment]
Hi, my beacon node is a bit overwhelmed by the requests needed to serve the Merge dashboard. I increased the timeout to 2.5x of its previous value and it seems to be working now.

The issue is caused by the new validators - there's a check for their initial balances which need to be retrieved from the beacon node on-demand and these requests take quite long.

Let me know if it works for you now!

**Comment by Tachyonica** [comment]
Thanks!
